import { ResearchHeader, ResearchFooter } from "../research-shell";
import { docsUrl, repoUrl, sitePath, pageMetadata, publishedVersion } from "../site-metadata";
import styles from "../research.module.css";
export const metadata = pageMetadata("CRISPR guide counting: FASTQ to MAGeCK counts | DotMatch", "Count known CRISPR guides from FASTQ, review read-window inference and ambiguity, and hand off MAGeCK-compatible counts with reproducible methods.", "crispr-guide-counting");
export default function CrisprCounting() {
  return <><ResearchHeader /><main id="main-content" className={styles.shell}>
    <header className={styles.pageHeader}><p className={styles.breadcrumb}><a href={sitePath()}>DotMatch</a> / CRISPR guide counting</p><p className={styles.eyebrow}>A local, reviewable workflow</p><h1 className={styles.title}>From FASTQ to CRISPR guide counts.</h1><p className={styles.lede}>Start with sequencing reads and a known guide library. Review the extraction window, count compatible reads, and inspect what was left out before downstream screen analysis.</p><div className={styles.actions}><a className={styles.primary} href="#first-run">Start a first run</a><a className={styles.secondary} href={sitePath("tools/library-safety")}>Check your library first</a></div></header>
    <section className={styles.section}><h2>What goes in. What comes out.</h2><div className={`${styles.grid} ${styles.two}`}><article className={styles.card}><h3>Inputs</h3><p>A guide CSV/TSV with IDs and sequences, and FASTQ files for your samples. Keep sample identity, guide orientation, assay layout, and gene annotations explicit.</p></article><article className={styles.card}><h3>Outputs</h3><p>MAGeCK-compatible guide-by-sample counts, assignment QC, reports, and a reproducible handoff. DotMatch does not run gene-level significance testing or infer biological hits.</p></article></div></section>
    <section id="first-run" className={styles.section}><h2>Prepare, review, then count.</h2><p>Install the published CLI. Use a new output directory so an earlier analysis is not overwritten.</p><pre className={styles.code}><code>{`python3 -m pip install dotmatch==${publishedVersion}\ndotmatch --version\n\ndotmatch crispr quickstart \\\n  --library guides.csv \\\n  --fastq 'fastqs/*.fastq.gz' \\\n  --out crispr_screen/`}</code></pre><p className={styles.note}>Before executing the assay, review <code>crispr_screen/inference_report.json</code> and <code>assay.toml</code>. Confirm the expected read window, orientation, library, and sample files. An inferred setting is a proposal, not a guarantee.</p><pre className={styles.code}><code>{`dotmatch assay start crispr_screen/assay.toml\n\n# After reviewing a completed run:\ndotmatch assay handoff crispr_screen/assay.toml`}</code></pre><p className={styles.caption}>The handoff includes configuration, reports, methods, and checksums without copying raw FASTQs. Review identifiers and other metadata before sharing it.</p><div className={styles.actions}><a className={styles.secondary} href={`${docsUrl}tutorials/crispr-count-first-run.html`}>Full first-run tutorial</a><a className={styles.secondary} href={`${docsUrl}lab-evaluation.html`}>Lab review checklist</a></div></section>
    <section className={styles.section}><h2>Choose correction rules deliberately.</h2><div className={styles.grid}><article className={styles.card}><h3>Exact matching</h3><p>Require the configured read window to equal a known target. Useful as a transparent baseline, but it does not recover substitution or indel errors.</p></article><article className={styles.card}><h3>Hamming matching</h3><p>Allow substitutions in equal-length windows. Inspect overlapping target neighbourhoods and the difference between radius and best-distance ambiguity policies.</p></article><article className={styles.card}><h3>Levenshtein matching</h3><p>Include insertions and deletions under the configured extraction and matching rules. Different semantics and costs require separate evidence, not a speed claim borrowed from exact matching.</p></article></div><p className={styles.note}>A higher assigned fraction is not automatically a more accurate result. Do not increase the mismatch allowance simply to improve a headline percentage. Inspect unmatched sequences, extraction failures, ambiguity, and changed assignments.</p><a href={sitePath("tools/library-safety")}>Inspect radius-one Hamming collisions in your browser</a></section>
    <section className={styles.section}><h2>Fit into an existing analysis, not replace it blindly.</h2><div className={styles.scroll} tabIndex={0} role="region" aria-label="Workflow comparison"><table className={styles.table}><caption>Different tools perform different parts of the job</caption><thead><tr><th scope="col">Workflow</th><th scope="col">How to evaluate the fit</th></tr></thead><tbody><tr><th scope="row">MAGeCK</th><td>Use DotMatch for counting when its assignment semantics fit your assay; retain downstream statistics. Compare count tables, not only runtime. <a href="https://sourceforge.net/p/mageck/wiki/Home/">MAGeCK documentation</a></td></tr><tr><th scope="row">guide-counter</th><td>Compare equal offset, mismatch, and ambiguity policies. It supports one-mismatch/no-indel and exact-counting routes. <a href="https://github.com/fulcrumgenomics/guide-counter">Official guide-counter repository</a></td></tr><tr><th scope="row">nf-core/crisprseq</th><td>A supplied count table is an integration route, not proof of an accepted DotMatch module. Validate the pinned pipeline version, headers, sample names, and gene identifiers; its documented columns include <code>sgRNA</code> and <code>gene</code>. <a href="https://nf-co.re/crisprseq/usage/screening/">Official screening workflow</a></td></tr><tr><th scope="row">Adapter-aware processing</th><td>Variable read structures may need upstream extraction or trimming rather than a single fixed window. Record those transformations in the analysis methods.</td></tr></tbody></table></div></section>
    <section className={styles.section}><h2>Read benchmark status as evidence, not a verdict.</h2><p>The public comparison report separates exact, Hamming, and Levenshtein results. Some rows marked <code>ok</code> still contain differing guide counts. That status alone does not establish count identity or biological correctness.</p><p>Inspect dataset and sample scope, repeated versus full-file runs, per-guide differences, and the reference implementation used. Oracle agreement checks algorithmic behaviour under defined rules; it does not reveal a read’s true biological origin.</p><div className={styles.actions}><a className={styles.secondary} href={`${docsUrl}benchmarks/crispr_comparison/README.html`}>Inspect the comparison report</a><a className={styles.secondary} href={`${repoUrl}/tree/main/examples/crispr_guides`}>Reproduce a public example</a></div></section>
    <section className={styles.section}><h2>Working with Perturb-seq?</h2><p>Guide-capture read assignment is one stage. Cell-barcode correction, UMI processing, ambient-guide filtering, guide-per-cell calls, expression analysis, and perturbation effects require additional methods. Do not interpret per-read counts as completed single-cell analysis.</p><a href={`${docsUrl}tutorials/scverse-perturb-seq.html`}>Review the feature-matrix and scverse boundary</a></section>
  </main><ResearchFooter /></>;
}
