import packageMetadata from "../package.json";
import checkedFixtureEnvelope from "../agent-reference-crispr.json";
import { ResearchHeader, ResearchFooter } from "./research-shell";
import { basePath, canonicalUrl, conceptDoi, docsUrl, publishedVersion, repoUrl, sitePath } from "./site-metadata";
import styles from "./research.module.css";
const structuredData = {
  "@context": "https://schema.org", "@graph": [
    { "@type": "WebSite", "@id": `${canonicalUrl()}#website`, name: "DotMatch", url: canonicalUrl(), description: "CRISPR guide counting and known-target barcode assignment with visible ambiguity and QC." },
    { "@type": "SoftwareApplication", "@id": `${canonicalUrl()}#software`, name: "DotMatch", applicationCategory: "Bioinformatics software", operatingSystem: "Linux, macOS", softwareVersion: publishedVersion, softwareHelp: docsUrl, codeRepository: repoUrl, downloadUrl: "https://pypi.org/project/dotmatch/", citation: conceptDoi, license: `${repoUrl}/blob/main/LICENSE`, programmingLanguage: ["C", "Python", "R"], featureList: ["CRISPR guide counting", "MAGeCK-compatible count tables", "inline barcode demultiplexing", "known-target library auditing", "explicit ambiguous-read outcomes"], description: "Assign short read windows to known DNA targets. Review unique, ambiguous, unmatched, and invalid reads before downstream analysis." }
  ]
};
const outcomes = [["unique", "One target fits the selected assignment rule."], ["ambiguous", "Several targets fit. No forced assignment."], ["none", "No target fits. Investigate unmatched reads."], ["invalid", "The requested read window cannot be extracted."]];
export default function Home() {
  return <><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData) }} /><ResearchHeader />
    <main id="main-content" className={styles.shell}>
      <section id="top" className={styles.hero} aria-labelledby="hero-title"><div>
        <p className={styles.eyebrow}>CRISPR guide counting & barcode QC</p><h1 id="hero-title" className={styles.title}>Guide counts you can inspect.</h1>
        <p className={styles.lede}>Turn FASTQ reads and a known guide library into count tables, assignment QC, and a reproducible handoff. Keep ambiguous reads visible instead of forcing them into the result.</p>
        <div className={styles.actions}><a className={styles.primary} href={sitePath("crispr-guide-counting")}>Count CRISPR guides</a><a className={styles.secondary} href={sitePath("tools/library-safety")}>Check a library in your browser</a></div>
        <p className={styles.caption}>Open source · Runs locally · Published CLI {publishedVersion}<br />Browser checker: no installation, account, or sequence upload.</p>
      </div><aside className={styles.panel} aria-labelledby="output-title"><p className={styles.eyebrow}>Your data → reviewable results</p><h2 id="output-title">FASTQ + guide library</h2>
        <ul className={styles.outputs}><li><code>MAGeCK-compatible counts</code><span>Guide-by-sample counts for downstream screen analysis.</span></li><li><code>Assignment QC</code><span>Unique, ambiguous, unmatched, and invalid outcomes.</span></li><li><code>Methods + checksums</code><span>A local handoff bundle without copying raw FASTQs.</span></li></ul>
        <pre className={styles.code}><code>{`python3 -m pip install dotmatch==${publishedVersion}\ndotmatch --version`}</code></pre><p className={styles.caption}>Counting and assignment, not gene-level significance testing.</p>
      </aside></section>
      <section id="workflow" className={styles.section} aria-labelledby="workflow-title"><p className={styles.eyebrow}>One understandable workflow</p><h2 id="workflow-title">From a guide library to counts you can explain.</h2>
        <div className={styles.grid}><article className={styles.card}><h3>1. Prepare</h3><p>Provide a guide library and FASTQs. Review the inferred window and assay configuration before counting.</p><a href={sitePath("crispr-guide-counting")}>Follow the CRISPR workflow</a></article><article className={styles.card}><h3>2. Check correction risk</h3><p>Inspect duplicate sequences and overlapping mismatch neighbourhoods. A larger correction radius is not automatically better.</p><a href={sitePath("tools/library-safety")}>Try the library checker</a></article><article className={styles.card}><h3>3. Review and hand off</h3><p>Inspect assignment outcomes, then carry counts and methods into your statistical workflow.</p><a href={`${docsUrl}lab-evaluation.html`}>Review a completed run</a></article></div>
        <figure className={styles.figure}><picture><source media="(max-width: 520px)" srcSet={`${basePath}/dotmatch-read-assignment-mobile-v2.webp`} width="864" height="1821" /><img src={`${basePath}/dotmatch-read-assignment-v2.webp`} width="1825" height="862" alt="FASTQ reads and a target library pass through fixed-window assignment into unique, ambiguous, unmatched, and invalid outcomes" loading="lazy" decoding="async" /></picture><figcaption>Known-target sequencing read assignment: compare a reviewed read window with the sequences you expect.</figcaption></figure>
      </section>
      <section id="failure-modes" className={styles.section} aria-labelledby="outcomes-title"><h2 id="outcomes-title">Account for reads that do not become counts.</h2><p>Review the matching rule, window, orientation, and library alongside these outcomes.</p><div className={`${styles.grid} ${styles.two}`}>{outcomes.map(([label, detail]) => <article key={label} className={styles.card}><h3><code>{label}</code></h3><p>{detail}</p></article>)}</div><p className={styles.note}>A unique assignment is not proof of biological origin. Contamination, missing targets, and errors outside the matching model still matter. <a href={`${docsUrl}trust-and-scope.html`}>Read the scientific boundaries.</a></p></section>
      <section id="use-cases" className={styles.section} aria-labelledby="uses-title"><h2 id="uses-title">Start with the job you need done.</h2><div className={styles.grid}>
        <article className={styles.card}><h3>CRISPR screens</h3><p>Count known CRISPR guides and export MAGeCK-compatible tables. Keep hit calling in a dedicated statistics workflow.</p><a href={sitePath("crispr-guide-counting")}>FASTQ to guide counts</a></article>
        <article className={styles.card}><h3>Barcodes & core facilities</h3><p>Demultiplex fixed-position inline barcodes, inspect collisions, and diagnose unmatched or ambiguous reads.</p><a href={`${docsUrl}getting-started.html#diagnose-a-barcode-run`}>Troubleshoot barcode assignment</a></article>
        <article className={styles.card}><h3>Feature & guide capture</h3><p>Assign known feature sequences. Build a cell-by-feature matrix from already extracted, cell-labelled observations; upstream cell/UMI processing stays separate.</p><a href={`${docsUrl}tutorials/scverse-perturb-seq.html`}>See the scverse handoff</a></article>
      </div></section>
      <section id="evidence" className={styles.section} aria-labelledby="evidence-title"><p className={styles.eyebrow}>Inspect the evidence</p><h2 id="evidence-title">Published inputs. Explicit comparisons. Reproducible methods.</h2><div className={styles.grid}>
        <article className={styles.card}><h3>Public CRISPR comparisons</h3><p>Inspect Yusa and Brunello results, count differences, commands, and resource measurements. Exact, Hamming, and Levenshtein comparisons are different lanes.</p><a href={`${docsUrl}benchmarks/crispr_comparison/README.html`}>Read the comparison report</a></article>
        <article className={styles.card}><h3>Direct-guide case study</h3><p>The GSE146194 case study separates discovery from evaluation reads and checks assignment against reference implementations. It does not validate guide-per-cell calls.</p><a href={`${repoUrl}/tree/main/examples/perturb_seq_gse146194`}>Reproduce the case study</a></article>
        <article className={styles.card}><h3>Methods & citation</h3><p>Review assignment semantics, release archives, and output contracts before adopting DotMatch in a study.</p><a href={`${docsUrl}methods-and-citation.html`}>Methods and citation</a></article>
      </div><p className={styles.note}>A benchmark row marked <code>ok</code> does not by itself mean identical counts or biological correctness. Inspect count deltas, semantics, dataset scope, and validation method. <a href={sitePath("crispr-guide-counting")}>Interpret the evidence.</a></p></section>
      <section id="install" className={styles.section} aria-labelledby="install-title"><h2 id="install-title">Use your existing research environment.</h2><p>Install the published Linux or macOS CLI from PyPI, or follow the Conda and container instructions. Check the installed version: community distribution channels can lag a release.</p><pre className={styles.code}><code>{`python3 -m pip install dotmatch==${publishedVersion}\ndotmatch --version\ndotmatch crispr quickstart --help`}</code></pre><div className={styles.actions}><a className={styles.primary} href={`${docsUrl}getting-started.html`}>Installation & first run</a><a className={styles.secondary} href={`${repoUrl}/tree/main/examples/workflows`}>Workflow examples</a></div><p className={styles.caption}>Published package: {publishedVersion}. Website source version: {packageMetadata.version}. Local wrappers are not claims of acceptance into an upstream platform.</p></section>
      <section id="agent-workflow" className={styles.section} aria-labelledby="agent-title"><h2 id="agent-title">Automate a reviewed workflow.</h2><p>Local agents can prepare, preflight, run, review, and package an assay through six structured tools. The same scientific checks apply whether a person or an agent starts the run.</p><pre className={styles.code}><code>{`dotmatch agent tools --json\ndotmatch agent export-skill --target ./dotmatch-agent`}</code></pre><div className={styles.actions}><a className={styles.secondary} href={`${docsUrl}agent-guide.html`}>Agent guide</a><a className={styles.secondary} href={`${basePath}/agent-capabilities.json`}>Capability manifest</a></div><details className={styles.detail}><summary>Inspect the synthetic agent-contract fixture</summary><p>This fixture intentionally exercises unsafe and low-assignment states. Its expected verdict is <code>failed</code>; it is a software contract test, not biological validation.</p><pre className={styles.code}><code>{JSON.stringify(checkedFixtureEnvelope, null, 2)}</code></pre></details><p className={styles.caption}>DotMatch is not a genome aligner, basecaller, cell-calling pipeline, or downstream screen statistics package.</p></section>
    </main><ResearchFooter /></>;
}
