import { ResearchHeader, ResearchFooter } from "../../research-shell";
import { pageMetadata, sitePath, docsUrl, repoUrl } from "../../site-metadata";
import { LibraryExplorer } from "./explorer";
import styles from "../../research.module.css";
export const metadata = pageMetadata("Barcode & guide library collision checker | DotMatch", "Check duplicate target sequences and ambiguous one-base corrections in your browser. Exact Hamming radius-one audit; no sequence uploads or installation.", "tools/library-safety");
export default function LibrarySafety() {
  return <><ResearchHeader /><main id="main-content" className={styles.shell}>
    <header className={styles.pageHeader}><p className={styles.breadcrumb}><a href={sitePath()}>DotMatch</a> / Library checker</p><p className={styles.eyebrow}>Free research tool · No installation · No upload</p><h1 className={styles.title}>Can a one-base correction confuse your targets?</h1><p className={styles.lede}>Inspect duplicate sequences, exact-read ambiguity, and overlapping single-substitution neighbourhoods. Your library is processed in this browser, without sending sequences to a server.</p><p className={styles.caption}>This is an assignment-collision checker, not a CRISPR off-target cutting, editing-efficiency, or clinical-safety assessment.</p></header>
    <LibraryExplorer />
    <section className={styles.section}><h2>What is counted?</h2><p>For every supplied sequence of length L, the audit enumerates the exact sequence and all 3L single-base substitutions. An observation is ambiguous when it lies within one substitution of more than one supplied target ID. Shared observations are counted once, not once per conflicting pair.</p><div className={styles.grid}><article className={styles.card}><h3>Targets one base apart</h3><p>Even an exact read can fit both targets under radius-one matching. A best-distance policy would treat an exact match differently.</p></article><article className={styles.card}><h3>Targets two bases apart</h3><p>The exact target sequences remain distinct, but their one-substitution neighbourhoods overlap.</p></article><article className={styles.card}><h3>Targets at least three bases apart</h3><p>Their radius-one Hamming neighbourhoods are disjoint. This is a statement about the supplied library and matching model, not the accuracy of an entire assay.</p></article></div><p className={styles.note}>A 20-base target has 60 possible single-substitution observations. The number that is ambiguous is not an estimated error probability: actual sequencing errors are not assumed to be equally likely.</p></section>
    <section className={styles.section}><h2>Limits that matter.</h2><p>This audit uses all supplied target rows, supplied orientation, A/C/G/T sequences of equal length, and Hamming radius one. Duplicate sequences remain separate candidates when their IDs differ. No automatic deduplication, sequence repair, reverse-complement search, indel model, or quality weighting is applied.</p><p>A unique assignment can still be wrong because the true target is missing, contamination is present, or the error process exceeds the model. No green score or biological confidence percentage is inferred from collision-free geometry.</p><p>The browser limit is 2,000 targets of 8–32 bases. Large libraries are rejected, not silently sampled. Only the displayed table and witness list are shortened; the completed JSON report contains every target’s audit.</p></section>
    <section className={styles.section}><h2>Move from a library check to an assay workflow.</h2><p>Use the native audit for a larger library and review its configured metric and semantics. This small exhaustive implementation is independent of the native engine and is not a native-performance benchmark.</p><pre className={styles.code}><code>{`dotmatch audit --help\n\ndotmatch audit \\\n  --targets guides.tsv \\\n  --k 1 \\\n  --audit-mode auto \\\n  --out-dir audit/`}</code></pre><div className={styles.actions}><a className={styles.primary} href={sitePath("crispr-guide-counting")}>Count CRISPR guides</a><a className={styles.secondary} href={`${docsUrl}barcode-panel-design.html`}>Native library and panel documentation</a></div><p className={styles.caption}><a href={`${repoUrl}/blob/main/lib/library-safety.ts`}>Inspect the algorithm</a> · <a href={`${repoUrl}/blob/main/tests/site/library-safety.test.mjs`}>Inspect the reference tests</a></p></section>
  </main><ResearchFooter /></>;
}
