#!/usr/bin/env python3
"""Generate the DotMatch public evidence gallery from a JSON manifest."""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
from typing import Any


GALLERY_DIR = Path("docs") / "evidence-gallery"
MANIFEST = GALLERY_DIR / "manifest.json"
GENERATED_HEADER = "<!-- Generated by scripts/generate_evidence_gallery.py; edit manifest.json instead. -->"
STATUS_LABELS = {
    "supported": "Documented example",
    "gated": "Validation milestone",
    "smoke": "Small fixture",
}


def _load_manifest(root: Path) -> dict[str, Any]:
    return json.loads((root / MANIFEST).read_text(encoding="utf-8"))


def _scenarios(manifest: dict[str, Any]) -> list[dict[str, Any]]:
    scenarios = manifest.get("scenarios") or []
    return [scenario for scenario in scenarios if isinstance(scenario, dict)]


def _as_list(value: object) -> list[str]:
    if not isinstance(value, list):
        return []
    return [str(item) for item in value]


def _rel_link(from_file: Path, repo_path: str) -> str:
    target = Path(repo_path)
    if target.is_absolute():
        return repo_path
    from_dir = from_file.parent
    return os.path.relpath(target, start=from_dir).replace(os.sep, "/")


def _link(from_file: Path, repo_path: str, label: str | None = None) -> str:
    label = label or repo_path
    return f"[{label}]({_rel_link(from_file, repo_path)})"


def _escape_cell(value: object) -> str:
    return str(value).replace("|", "\\|").replace("\n", " ")


def _bullet_links(from_file: Path, paths: list[str]) -> list[str]:
    return [f"- {_link(from_file, path, path)}" for path in paths]


def _status_label(status: object) -> str:
    return STATUS_LABELS.get(str(status), str(status or ""))


def render_index(manifest: dict[str, Any]) -> str:
    out = GALLERY_DIR / "README.md"
    scenarios = _scenarios(manifest)
    lines = [
        GENERATED_HEADER,
        "",
        "# DotMatch Evidence Gallery",
        "",
        str(manifest.get("summary") or "Public evidence, benchmark reports, and report examples for DotMatch."),
        "",
        "Start here when you want to see what DotMatch does on real or deliberately diagnostic data.",
        "Each row links to the exact report, raw artifacts, command records, and a short interpretation.",
        "",
        "## Gallery",
        "",
        "| Scenario | Category | Dataset | What it shows | Primary report |",
        "| --- | --- | --- | --- | --- |",
    ]
    for scenario in scenarios:
        scenario_doc = f"docs/evidence-gallery/scenarios/{scenario['id']}.md"
        lines.append(
            "| {scenario} | {category} | {dataset} | {condition} | {report} |".format(
                scenario=_link(out, scenario_doc, _escape_cell(scenario.get("title", scenario["id"]))),
                category=_escape_cell(scenario.get("category", "")),
                dataset=_escape_cell(scenario.get("dataset", "")),
                condition=_escape_cell(scenario.get("condition", "")),
                report=_link(out, str(scenario.get("primary_report", "")), "report"),
            )
        )
    lines.extend(
        [
            "",
            "## Report Examples",
            "",
            _link(out, "docs/evidence-gallery/report-zoo/README.md", "Open the report examples")
            + " for clean runs, weak barcode signal, wrong-window symptoms, unsafe correction, and validation milestones.",
            "",
            "## How To Read These Pages",
            "",
            "- Each scenario separates the observed result from what it does not establish.",
            "- Comparator settings are part of the evidence. Changing them changes the meaning of the result.",
            "- HTML, TSV, JSON, FASTQ, and raw CSV files are linked directly when they are committed.",
            "",
        ]
    )
    return "\n".join(lines)


def render_report_zoo(manifest: dict[str, Any]) -> str:
    out = GALLERY_DIR / "report-zoo" / "README.md"
    role_names = {
        "known_good": "Known-good public data",
        "low_confidence": "Low-confidence inference or weak signal",
        "wrong_offset": "Wrong offset or wrong fixed window",
        "unsafe_correction": "Unsafe one-edit correction",
        "many_unmatched": "Many unmatched or ambiguous reads",
        "gated_parser_milestone": "Narrow parser milestone",
    }
    lines = [
        GENERATED_HEADER,
        "",
        "# DotMatch Report Examples",
        "",
        "These examples show what DotMatch reports look like under common run conditions.",
        "Use them to compare a new run against a known-good lane or a known failure pattern.",
        "",
    ]
    scenarios = _scenarios(manifest)
    for role, title in role_names.items():
        matching = [scenario for scenario in scenarios if role in _as_list(scenario.get("gallery_roles"))]
        if not matching:
            continue
        lines.extend([f"## {title}", ""])
        for scenario in matching:
            scenario_doc = f"docs/evidence-gallery/scenarios/{scenario['id']}.md"
            lines.append(f"- {_link(out, scenario_doc, str(scenario.get('title', scenario['id'])))}: {scenario.get('condition', '')}")
        lines.append("")
    return "\n".join(lines)


def render_scenario(scenario: dict[str, Any]) -> str:
    out = GALLERY_DIR / "scenarios" / f"{scenario['id']}.md"
    report_examples = scenario.get("report_examples") or []
    lines = [
        GENERATED_HEADER,
        "",
        f"# {scenario.get('title', scenario['id'])}",
        "",
        f"- Category: `{scenario.get('category', '')}`",
        f"- Assay type: `{scenario.get('assay_type', '')}`",
        f"- Evidence level: {_status_label(scenario.get('status'))}",
        f"- Dataset: {scenario.get('dataset', '')}",
        f"- Condition shown: {scenario.get('condition', '')}",
        f"- Primary report: {_link(out, str(scenario.get('primary_report', '')), str(scenario.get('primary_report', '')))}",
        "",
        "## What This Shows",
        "",
    ]
    lines.extend(f"- {item}" for item in _as_list(scenario.get("proves")))
    lines.extend(["", "## What It Does Not Show", ""])
    lines.extend(f"- {item}" for item in _as_list(scenario.get("limits")))
    lines.extend(["", "## Comparator And Validation", "", f"Comparator semantics: {scenario.get('comparator_semantics', '')}", "", f"Validation: {scenario.get('validation', '')}", ""])
    if report_examples:
        lines.extend(["## Report Examples", ""])
        for example in report_examples:
            if not isinstance(example, dict):
                continue
            label = str(example.get("label") or example.get("path") or "report")
            path = str(example.get("path") or "")
            kind = str(example.get("kind") or "artifact")
            lines.append(f"- {_link(out, path, label)} (`{kind}`)")
        lines.append("")
    raw_artifacts = _as_list(scenario.get("raw_artifacts"))
    if raw_artifacts:
        lines.extend(["## Raw Artifacts", "", *_bullet_links(out, raw_artifacts), ""])
    commands = _as_list(scenario.get("commands"))
    if commands:
        lines.extend(["## Reproduce Or Check", ""])
        lines.extend(f"- `{command}`" for command in commands)
        lines.append("")
    return "\n".join(lines)


def render_files(root: Path) -> dict[str, str]:
    manifest = _load_manifest(root)
    files = {
        (GALLERY_DIR / "README.md").as_posix(): render_index(manifest),
        (GALLERY_DIR / "report-zoo" / "README.md").as_posix(): render_report_zoo(manifest),
    }
    for scenario in _scenarios(manifest):
        path = GALLERY_DIR / "scenarios" / f"{scenario['id']}.md"
        files[path.as_posix()] = render_scenario(scenario)
    return files


def write_gallery(root: Path) -> None:
    for rel_path, text in render_files(root).items():
        path = root / rel_path
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text.rstrip() + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", default=".", help="repository root")
    args = parser.parse_args()
    write_gallery(Path(args.root).resolve())
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
