from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]

PUBLIC_PATHS = [
    ROOT / "README.md",
    ROOT / "DESCRIPTION",
    ROOT / "docs",
    ROOT / "examples",
    ROOT / "app",
    ROOT / "public",
    ROOT / "python" / "dotmatch",
    ROOT / ".github",
]

PUBLIC_SUFFIXES = {".css", ".html", ".json", ".md", ".mdx", ".nf", ".py", ".ts", ".tsx", ".xml", ".yaml", ".yml"}
SKIP_PARTS = {"_build", "node_modules", "__pycache__"}

FORBIDDEN_PHRASES = [
    "adoption " + "evidence",
    "adoption " + "trust",
    "ai " + "slop",
    "big " + "wins",
    "evidence-" + "bounded",
    "industry " + "exposure",
    "massive industry " + "impact",
    "next " + "wins",
    "pilot " + "conversations",
    "private " + "feedback",
    "quote-" + "approved",
    "turning private evaluation into public adoption " + "evidence",
    "without turning private feedback into public " + "evidence",
    "industry " + "penetration",
    "massive industry " + "penetration",
    "international computational biology " + "infiltration",
    "totally super " + "massive",
    "excellent " + "ux",
    "perfect scientific " + "accuracy",
    "adoption " + "flywheel",
    "adoption " + "kpi",
    "pilot " + "scorecard",
    "release communications " + "calendar",
    "routes into industry " + "workflows",
    "give each evaluator a " + "next step",
    "people who can " + "spread dotmatch",
    "what the homepage can safely " + "claim",
    "copy-paste " + "ready",
    "workflow & pipeline " + "penetration",
    "pypi and bioconda are verified for v0." + "1.8",
    "community " + "traction",
    "evaluator " + "campaign",
    "generated by " + "codex",
    "agent contribution " + "policy",
]


def _public_files():
    for path in PUBLIC_PATHS:
        if path.is_file():
            yield path
            continue
        if not path.exists():
            continue
        for candidate in path.rglob("*"):
            if not candidate.is_file() or candidate.suffix.lower() not in PUBLIC_SUFFIXES:
                continue
            if SKIP_PARTS.intersection(candidate.relative_to(ROOT).parts):
                continue
            yield candidate


def test_public_language_avoids_internal_process_phrasing():
    failures = []
    for path in _public_files():
        text = path.read_text(encoding="utf-8").lower()
        for phrase in FORBIDDEN_PHRASES:
            if phrase in text:
                failures.append(f"{path.relative_to(ROOT)} contains forbidden phrase: {phrase}")

    assert failures == []
